### ISSUE TITLE
Dropdown menu should include link to contribute guide

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotblog#10]
This menu:
![image](https://user-images.githubusercontent.com/1300499/70269496-81391800-1770-11ea-9502-577b064e9e76.png)
should include a link to the [contribute guide](https://matplotlib.org/matplotblog/posts/how-to-contribute/) 'cause otherwise it will very quickly get lost in the blog posts- it's already off the first page.

**Comment by davidevaleriani** [comment]
Thanks for the suggestion, done.
