### ISSUE TITLE
Attempting to contribute - Permission denied when attempting to push

### ISSUE THREAD

**Issue by tdpetrou** [matplotlib/matplotblog#14]
I was asked to contribute and am following the steps on [How to Contribute](https://matplotlib.org/matplotblog/posts/how-to-contribute/). The post looks good locally on hugo and I'm ready to make a pull request. Running the command `git commit -am "my message"` doesn't add anything and responds with the following message:

> nothing added to commit but untracked files present

Manually adding files with `git add content/posts/post-my-post-name' and then committing and pushing gives me the following error:

> The current branch post-create-a-tesla-cybertruck-that-drives has no upstream branch.

It advises me to add an upstream branch with

`git push --set-upstream origin post-my-post-name`

which ultimately denies me permission

> remote: Permission to matplotlib/matplotblog.git denied to tdpetrou.

Should I just fork the repo and create a pull request that way?

**Comment by davidevaleriani** [comment]
I guess you've figured out how to do a PR :) Thanks!

**Comment by tdpetrou** [comment]
Thanks for adding my contribution! I wrote this issue to showcase how the steps in the How to Contribute document do not work. I believe I followed them verbatim. I am aware of how to make pull requests by forking repos, making changes, and then making the request. I noticed other pull requests were done similarly.

Does the How to Contribute document need to be updated?

**Comment by davidevaleriani** [comment]
Thanks for pointing this out. I have clarified that you need first to add your new post to the repository, before committing, by doing:
`git add your-fancy-title`
Then, everything should go smoothly as described.
