### ISSUE TITLE
matplotblog May 27, 2020  typo, should be:  plt.plot( time, distance, 'bo-')

### ISSUE THREAD

**Issue by gplanansky** [matplotlib/matplotblog#43]
first code block, line 4:
second code block, line 3:
third code block, line3:
``plt.plot(distance,'bo-')`` should be ``plt.plot(time, distance, 'bo-')``

I did not see a comment section at the blog itself.

**Comment by story645** [comment]
Hi, thanks for the report. Transferred this issue to the blog repository. Would you be interested in opening a PR to fix the typos?

**Comment by gplanansky** [comment]
Sure (where is the blog repository?);  good to learn to do this.  Could you
tell me the recipe for opening a PR?  thanks.

**Comment by story645** [comment]
The repo is https://github.com/matplotlib/matplotblog

If you want full instructions, they're at https://matplotlib.org/matplotblog/posts/how-to-contribute/

The pr through gui steps are:
1. fork this repo
2. on your fork, find the file with the typo 
3. fix it & commit the change to a new branch 
4. press the "open pull request" button
5. select matplotblog:master as the target (arrow points towards it: matplotblog:master<-)
6. Submit the pull request.

More info at 
https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request

**Comment by davidevaleriani** [comment]
This has been fixed, so closing it
